# Generated by Django 2.2.7 on 2019-11-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='iso_code',
        ),
    ]
