# Generated by Django 2.2.7 on 2019-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_remove_country_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='electricity_access',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='energy_consumption',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
