# Generated by Django 2.2.7 on 2019-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20191130_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='electricity_access',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='energy_consumption',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
