# Generated by Django 2.2.7 on 2019-12-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20191130_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='electricity_access',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='energy_consumption',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
