# Generated by Django 2.2.7 on 2019-12-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_auto_20191201_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
